[package]
name = "zstarkwarp"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.2" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.2" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.2" }
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.18.2" }

[dev-dependencies]
snforge_std = "0.52.0"
assert_macros = "2.11.4"

[cairo]
sierra-replace-ids = false # Do not forget this to avoid compilation errors.

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[features]
enable_for_tests = []